### ISSUE TITLE
Remove file from anaconda cloud

### ISSUE THREAD

**Issue by glemaitre** [conda-forge/pydicom-feedstock#9]
@jakirkham Do you know if we can remove a file from the anaconda cloud:

https://anaconda.org/conda-forge/pydicom/files

The tag in github contained a `v` in the versioning which does not trigger to install the last version with the previous setting. So, I would like to remove `noarch/pydicom-v1.0.1-py_0.tar.bz2` to avoid any confusion for users when checking the versions.

**Comment by jakirkham** [comment]
We don't typically remove files. However have labeled that package as `broken`, which means it should not be downloaded unless the user pulls down packages from the `broken` label explicitly. Please confirm that I got the right one.

**Comment by glemaitre** [comment]
Perfect.
